import type { NextPage } from 'next'
import Head from 'next/head'
import Tweet from '../components/Tweet'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Twitter Clone
        </h1>
        <Tweet />
      </main>

    </div>
  )
}

export default Home
